version: '3.7'
services:
  redis:
    hostname: redis
    image: "redis:alpine"
    command: --port 6379
    ports:
      - "6379:6379"
    expose:
      - "6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
      